# when a push is done in another branch than master, create an ecr repository
# associated with this branch and build + push the image
name: ci-npm-docker

on: 
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches
    branches-ignore:
      - main
    paths:
      - 'vote-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'vote-app/**'
  workflow_dispatch:

env: 
  AWS_REGION: eu-north-1
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }}
  APP: vote-app
  # ECR_REPOSITORY: cadec23-demo-${{ github.ref_name }}
  # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
  # SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/skip-based-on-commit-message#just-use-yaml-recommended
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Github variables
      run: |
        echo github.event.ref: ${{ github.event.ref }}
        echo github.ref_type: ${{ github.ref_type }}
        echo github.ref_name: ${{ github.ref_name }}
        echo github.sha: ${{ github.sha }}
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        echo env.SHORT_SHA: ${{ env.SHORT_SHA }}
        
    - name: Clone
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        # username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # password: ${{ secrets.DOCKER_HUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: vote-app
        push: true
        build-args: |
          NODE_ENV=${{ github.ref_name }}
          VERSION=${{ env.SHORT_SHA }}
        tags: |
          ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.APP }}:${{ env.SHORT_SHA }}
          ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.APP }}:latest

    - name: Update image tag in K8S manifest
      run: | 
        cd ./vote-app/argocd-app-config/dev 
        sed -i .bak 's+andtell/vote-app:.*$*+andtell/vote-app:'${{ env.SHORT_SHA }}'+' deployment.yaml
      # bash ./vote-app/argocd-app-config/updateVersion.sh 
      #  chmod +x updateVersion.sh
      #  updateVersion.sh ${{ env.SHORT_SHA }}
      #shell: bash  
      #working-directory: vote-app/argocd-app-config

    - name: Commit image version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bumping image version to ${{ env.SHORT_SHA }}
          

